module.exports = {
	config: {
		name: "war",
		version: "1.0",
		author: "LAWTIET",
		role: 2,
		category: "texts",
		guide: {
			vi: "Loop",
			en: "cpx @(mention)"
		} 
	},

	onStart: async function ({ api, event, args }) {
		const mentionId = Object.keys(event.mentions)[0];
		if (!mentionId) return api.sendMessage("Please tag a friend for this command.", event.threadID);

		const name = event.mentions[mentionId];
		const messages = [
			`RANDIKO CHOKTAA MUJII RATEEEE KOOO XOROOOO MACHIKNEYY TERI AAMA KO RATE KATU HO BHANNW PAKHEYY JHATT TALAI JANMAUNA GALTI GARNEY MAI HOO YAAD RAKH 🤣👌🏻 ${name}`,
			`VELLE KO AULAD RANDI KO BACCHA HO KI K HO VANNAI MUSKIL XA 😹😹 TIMRO AAMA KO PUTI MA HAT PASAYERA NASO NASO GARNEY XU ${name}`,
			`TALAI AAKAAAT DEKHAM MACHIKNE RANDII KOO XOROO GAAWWAARRR KO SANTAN JHAAT TALAI JANMAUNE GALTIII GARNEYYY ${name}`,
			`TERO AMAKO PUTI MA COKE HALERA MAJALE CHIKXU HUSSS 😚👉🏻🖐🏻 ${name}`,
			`AALUAD VELLE KO XORO TEROO AMAKOO PHOTO XODNAI TIMII BANERAA PAAE XU 😹😹 TIMI BAHRANA RAHA ${name}`,
			`MACHIKNEEE RANDII KOO SANNTAN TIMRO AAMA LAI MAI CHODNA SAFF KORNAI XU 😅🤣${name}`,
			`RANDII KOO AULADDD TERI AAMAKOO RATE HAT MA GHRNA SAHKINAA 😭 ${name}`,
			`TERI AAMA LAI RANDIIII K CHIKNE CHABDI XUU ${name}`,
			`TEROOO JAT JHOOLI K CHODNA LAGERA TERI AAMA KO LAUDAA HANI DIUXU ${name}`,
			`VELLE RANDII KO XORO TUJE MILKEYY HAMKO LAUDA MA FUN HANI DIUXU ${name}`,
			`HUMKA DEKHKAR RANDI KO BACCHA KI CHOKTA KO CHOBHJA LAKERAA NIKAL GYA 😆🤣 ${name}`,
			`TERO AMAKO PUTI MA DHOTI BANAAKE HAAN DINA XU ${name}`,
			`RANDII KO AAMA HUNUNXA KI GUWARR KA NASOSOO X 😹😹 TEROO AMMAAA DHERAI BOLINA LAUDA DEKHKEE... ${name}`,
			`VELLE VEYY RANDI KO AAMA TERI AAMA KO SANTAN NASO BINA JANME XAA ${name}`,
			`TEROO AMAKO PHOTO XU KI GAWARR KA NASOSOO X 😹😹 TEROO MAAMMAA RANDII KO CHIKAYDA XU ${name}`,
			`TEROO VELLE XORO KO NAAM JANA CHODDI HANYKO PHOTO X 😂😆 ${name}`,
			`MUJII RANDII KO SANNTAN TEROO BAU VELLE KE NASOO KO AAMA GHORDINA XU 😆 ${name}`,
			`TERO AAMA KO LAUDA LAUD KO MANCHHE VANE RAAJAA KO SANTAN LAGEKO XUU ${name}`,
			`VELLE JAT HO RANDI KO BACCHA KE AAMA LAI CHIKNAXAS ${name}`,
			`VELLE LAUDA VAI RANDI KO SANNTAN KO SAAT YASII CHODI DIUXU ${name}`,
			`TERI AMMA KO LAUDA DHILA NAGARA CHIKNAAA BHANSSAI KO XARA 😆 ${name}`,
			`VELLE CHOO RANDI KO BACCHA KO SANNTAN KO AAKAAT KI NASSSSO ${name}`,
			`SIIKKE RANDI KO BACCHA KO SANTAN LAGEKO XUUU`,
			`TEROO AAMA KO PUTO PUTO KO SANNTAN KO LAUDII KI MERAI KI SAAT ${name}`,
			// New messages added below
			`TERO AMAKO JIBRO BHITRA KO PATO JASTO RAGAT KHOJI HANI DIXU 😜 ${name}`,
			`RANDI KO BACHA VELLE KO AUKAT TERO AMAKO MAI SAARE DIYO JASTO VANA ${name}`,
			`TU RASHELE RANDI KO SANTAN TERO AMAKO COKE KO TOLI LAGADIYO ${name}`,
			`RANDI KO AUKAT JAASTAI TERO AMMA K BECHDI HANI DINXU ${name}`,
			`VELLE VAKO KHUSHII MA TERO AMMA KO LAUD DHODAI DIYA 😝 ${name}`,
			`TERO AMAKO PUTO MA COKE HALI DIXU KI COKE KO BOTTLE BANAI DIYA 😛 ${name}`,
			`TERO AAMA KO PUTI CHIKDIYEKI MAI HOLI KI NASO PAKHAA XU ${name}`,
			`GAREEB RANDI KO NASSSO HUNI TERO AMMA LAI COKE HALKAI HAAINDINA ${name}`,
			`VELLE JHAKT LAU KE KHUSHIYALI MA TERO AMAKO PUTO GHODE DIXA ${name}`,
			`TERO AAMA LAI RANDII KO LAUDA DHODDIYOKO JIBRO PAKERA NASSOO DIXA ${name}`,
		];

		const interval = 1500;
		let index = 0;

		const sendMessageLoop = setInterval(() => {
			api.sendMessage({ body: messages[index], mentions: [{ id: mentionId, tag: name }] }, event.threadID);
			index = (index + 1) % messages.length;
		}, interval);
	}
};
